---
title: "Meth"
output: html_document
---

Here we'll try fit non parametric and parametric models. The last one incorporates an assumption about the age estructure of rates.

##IPF Method

Iterative proportional fitting (IPF) is a very known non parametric procedure to fit an array to a column and a row marginals already set with the same total count. The basic idea is to find successive row and column factors that replicates marginals (Schoen, 2003). 

The general framework is the use of log-linear models with a total count constraint, that consider the same two factor-effect (cross-product ratio), so high order interactions are dismissed. The IPF converges to MLE (unqiue set of row and column factors) for every initial values (Demig and Stephan, 1940).  Schoen (2003) propose an aditional arrangement of cells, called relative state attraction method, for giving to simmetry events an interpretation of contrary forces, inspired by matrix migration models, but the results are quiet simmilar to IPF, so we'll apply the basic approach. 

It's a saturated model (equal cells than parameters) with a solution that maximizes entropy, so it gives us the most uncertain scenario about flows, and without any additional structure in the results than in the marginals (Bishop, 2002). One advantage is that can handle structural zeroes (incomplete table), which is typical in chronic diseases where remission is not possible.

For each age there would be a contingency table, where the letter $e$ indicates the events in each cell. 

$$P_{x}^{t} =  \left(\begin{array}{cccc} 
                &  & \pi_{x,1}^{t+1} & \pi_{x,2}^{t+1} & \pi_{x,d}^{t+1}\\
                &  & \cdots & \cdots & \cdots\\
                \pi_{x,1}^{t} & \vdots & e_{x,11}^{t} & e_{x,12}^{t} & e_{x,1d}^{t}\\ 
                \pi_{x,1}^{t} & \vdots & 0 & e_{x,22}^{t} & e_{x,1d}^{t}\\ 
                 \end{array}\right)$$

Being the probability that an individual in state $i$ transit ate $j$ $\frac{e_{x,12}^{t}}{\pi_{x,1}^{t}}$.

For each target distribution, we need to know the "observable" distribution and a general mortality for $\pi_{x,d}^{t+1}$ that would be the probability of mortality from official life tables. 
Instead of doing the procedure for each age, we will arrange a matrix that contain all the contingency tables for all ages in its diagonal, so we don't have to loop the procedure. The final probability can be obtained in each row, in relation with the departure prevalence.  

In a demographic view, the result rates are those who...  


## r-variable
Schmertmann (2002) proposed a model for prevalence change using two cross-sectional sources. It is based in non-stable generalization, where there is an attribute that change with age, independetly of its decrement and increments at each age (Coale, 1985). This change can be decomposed into a intra-cohort effect, final objective of the methodology, non-negative in our case (incidence but not remission), and extra-cohort effects, like net-migration and death. In a closed population, only the last change is considered and is weigthed by the prevalence of those who leave the cohort. A disadvantaje of this method is that needs external information about relative risk ratio against overall mortality.   

The dinamic equation would be, for exact age-time prevalence (smoothed previously):
$$(\pi_{x}^{t})^{'} = \delta_{x,12}^{t} - \mu_{x,*d}^{t} (k_{x}^{t} - 1)\pi_{x}^{t}$$

From which one can obtain $\delta_{x,12}^{t}$ estimating the other terms, which is a net rate, not related with exposutes but with time. In the last one is included the prevalence of those who die, which is given by $k_{x}^{t} \pi_{x}^{t}$, being  $k_{x}^{t} = \frac{\mu_{x,2d}^{t}}{\mu_{x,*d}^{t}}$ a relative risk ratio but in relation with overall mortality. 
  
The derivative of the prevalence can be decomposed in partial derivatives, age and period effect: $(\pi_{x}^{t})^{'} = \frac{\partial\pi_{x}^{t}}{\partial t}+ \frac{\partial\pi_{x}^{x}}{\partial x}$. The key in his development is the linear approximation of those measures in a short period $h$. For example, for the "age effect"" we need to take the $h$ average effect of changing age in both periods:

$$\frac{\partial\pi_{x}^{t}}{\partial t} \approx \frac{1}{2} [\frac{\pi_{x+h}^{t}-\pi_{x}^{t}}{h} + \frac{\pi_{x+h}^{t+h}-\pi_{x}^{t+h}}{h}]$$  

An analogical calculus is done with period effect, and then average both. For the next step is required an estimation for the prevalence cohort during the exposition to dead, averaging corner values in the Lexis rectangle $(x,t), (x+h,t), (x,t+h), (x+h,t+h)$: $\bar{\pi}_{x,h}^{t,h}=[\pi_{x}^{t}+\pi_{x+h}^{t}+\pi_{x}^{t+h}+\pi_{x+h}^{t+h}]\frac{1}{4}$. 

Finally the estimated probability can be calculated like $\frac{\delta_{x,12}^{t}}{1-\pi_{x}^{t}}$.


# Intercensal method

This method is based in Guillot and Yu (2009), and consists in give a parametric shape to $p_{x,12}^{t,h}$ and $rr_{x}^{t,h}$ and insert this function in the "observable" cohort transition $\bar{\pi}_{x+h}^{t+h} = \bar{\pi}_{x}^{t} (1-p_{x,12}^{t,h}-p_{x,1d}^{t,h})$. 


Previously, an initial relationship between subgroups mortality must done $p_{x,*d}^{t,h} = \pi_{x}^{t}*p_{x,1d}^{t,h} + (1-\pi_{x}^{t})*p_{x,2d}^{t,h}$, which results in this expression of the not healthy mortality.


$$p_{x,1d}^{t,h} = \frac{p_{x,*d}^{t,h}}{\pi_{x}^{t}+(1-\pi_{x}^{t})*rr_{x}^{t,h}}$$

Knowing the overall mortality and with the assumption of $p_{x,12}^{t,h}=a_{1}e^{b_{1}x}$ and $rr_{x}^{t,h}=a_{2}e^{b_{2}x}$, there is a $age * 4$ system of equations, with constraints about the possible values of probabilities (between 0 and 1) and relative risk (greater than 1) and conservative bounds for the parametric shapes, than can be estimated with numerical methods.

The problem then is to find $k*=[a_{1}*,a_{2}*,b_{1}*,b_{2}*]$, such that minimize objective function, in this case the $MSE$ subject to the restrictions mentioned. Due to the non-linear relationships, and to the existence of derivative conditions with respect to x, we are facing a non-linear optimization problem with restrictions (Burden, 2002). The resolution technique is framed in the so-called sequential (of successive resolution of an optimization problem in each iteration), and is based on a Increased Lagrange function (Lagrange multipliers to incorporate constraints with inequalities, and a penalty term to force the direction of successive results, hence the "augmented") (Madsen et al., 2004).







